<a href="https://colab.research.google.com/github/n-aguiar/Data_Science/blob/main/Natalia_Aguiar%2C_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [15]:
for i in range(100):
    print(i) #prints the loop out

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [16]:
for i in range(5,8):
    print(i) #i is just a variable

5
6
7


In [17]:
for i in range(3):
    print( "Test Number: " , i ) # inserting a "x", makes in appear before the range stated above

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [18]:
def square(x):
    return x**2 #gives a function and action to a term

In [19]:
square(5)

25

In [20]:
square(square(2)) #i can insert the variable into itself just like a normal equation

16

In [21]:
square(square(square(2)))


256

In [22]:
square(123456)

15241383936

In [23]:
square(square(5))

625

In [24]:
def add_two(x):
    return x+2 

In [25]:
add_two(5)

7

In [26]:
square(add_two(5)) #adding the two variables made

49

### Logical Branching

In [27]:
choice = "apple" #sets a variable

In [28]:
if choice == "apple":

    print("You choose apples.") #making a decision oriented statement

else:
    
    print("You did not choose apples.")

You choose apples.


Changing the choice and keeping the code, creates a different outcome

In [29]:
choice = "orange"

In [30]:
if choice == "apple": 

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [31]:
choice = "apple"

In [32]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123) #prints a number sequence after

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!") #all that i write after print in the same vertical line will be printed our based on the choice

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [34]:
choice = input("Please enter your choice (i.e. apple): ") #input creates the oppurtunity for the person to make the decision

Please enter your choice (i.e. apple): apple


In [35]:
choice

'apple'

In [36]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges": #elif is like 2nd option

    print("You choose oranges.")

else: #else is anything else 
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [39]:
import numpy as np

In [49]:
np.random.random() #generates a random number 0<x<1

0.8429700161221361

In [57]:
np.random.random() > 0.5 #giving a range for the number either true or false

False

In [64]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads") #instead of writing true, we told the code that it is heads
    else:
        print("Tails") #instead of writing false, we told the code that it is tails

In [66]:
flip_coin() #testing the code

Tails


### Graphics Output

In [67]:
from IPython.core.display import display, HTML

In [68]:
display(HTML('<h1>Hello, world!</h1>')) #different <h'n'> values gives a different size

In [69]:
import numpy as np

In [70]:
def coin():
  return np.random.randint(2) #random.randint(x) gives an integer rather than decimal number

In [71]:
coin()

0

In [72]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

labeling the images to the correct variable

In [73]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [74]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) #src means search

In [78]:
show_img(heads) #making sure the right image appears

In [76]:
show_img(tails)

In [77]:
def flip_coin(): #making the coin flip action

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [79]:
flip_coin()

In [80]:
for i in range(5): # in rang just tells me that i want to flip x amount of coins
    flip_coin()

In [81]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [82]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1) #add 1 because eaxh integer starts from 0
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [83]:
a = np.arange(52) #setting a variable for the amound of cards

In [84]:
shuffle(a) #shuffle is self explanatory

array([ 3, 30, 27, 31, 43,  9,  0, 10, 24, 36, 51, 44, 13, 48,  8, 37, 19,
       42, 17, 23, 45, 33, 46, 47, 15,  2, 39,  4, 35, 14, 26, 11, 49, 25,
       21,  6, 34,  1, 22,  7, 50, 40, 16,  5, 32, 18, 38, 28, 41, 12, 20,
       29])

In [85]:
np.random.permutation(52)

array([11, 28, 31, 46, 43, 50,  7,  3, 29, 47, 35, 23, 41, 10,  2,  8,  1,
       34, 19, 25, 39,  5, 16, 15, 36, 49, 22, 40,  4,  0, 32, 12, 24, 45,
       18, 14, 17, 26, 21, 44, 20,  9, 27, 13, 33, 42,  6, 51, 38, 37, 30,
       48])

### Speed Test

In [86]:
%%timeit 
shuffle(a) #measures how long it takes to read the cell

170 µs ± 5.75 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [87]:
%%timeit
np.random.permutation(52) #time it takes to shuffle all 52 permutations

3.8 µs ± 298 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [88]:
import numpy as np

In [93]:
np.random.permutation(52) #random numbers from 0-51 for each card in the deck

array([42,  4,  6, 49,  8, 32, 16, 17,  9, 39, 11, 24, 37, 50, 31, 12, 34,
       22, 28, 23, 35,  2, 48, 38, 47,  3,  1, 29, 19, 36, 26, 21, 10, 43,
       46,  5, 27, 14, 13, 18, 20, 51, 40, 41, 25, 44, 15,  0, 45, 33,  7,
       30])

In [102]:
cards = np.random.permutation(52)

In [103]:
cards

array([ 1, 41, 28, 42, 48, 32, 34, 38,  9, 25, 18,  8, 19, 35, 37,  4, 21,
       29, 10, 13, 16, 46, 30, 43,  6,  7, 44, 50, 51, 39, 15,  0, 20,  2,
        5, 47, 26, 12, 23, 22, 40, 45, 11, 31, 27, 17, 33, 14, 24, 36, 49,
        3])

In [92]:
cards[0] #states which card in the order of th shuffle you want

16

In [106]:
cards[1] #each time the "cards" variable shuffles, this number changes

41

In [105]:
cards[2]

28

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [107]:
np.arange(52).reshape(4,13) #reshapes into 4 rows of 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13 #the percent divides each columns and restarts at 0 (makes the number of the cards)

In [ ]:
np.arange(52).reshape(4,13)//13 #the // seperates the rows into 4 (to make the suits)

In [117]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #put the name in the order of the suits in the image
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [111]:
def card_name(card_number):
    
    suit = card_number//13 
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [119]:
card_name(0)

'Ace of Clubs'

In [120]:
card_name(51)

'King of Diamonds'

In [121]:
cards = np.random.permutation(52)

In [115]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [116]:
top_of_deck, second_card_in_deck, last_card_in_deck #tells the cards in the order based on the current shuffle

('Queen of Diamonds', 'Queen of Hearts', 'Seven of Clubs')

In [123]:
for i in range(5): #just drawing cards from the deck
    print(card_name(cards[i]))

Seven of Diamonds
King of Clubs
Five of Diamonds
Three of Hearts
Two of Spades


In [124]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Diamonds
King of Clubs
Five of Diamonds
Three of Hearts
Two of Spades
Four of Clubs
Ten of Spades
Six of Hearts
Eight of Clubs
Three of Clubs
Nine of Spades
Nine of Hearts
Queen of Clubs
Jack of Spades
Queen of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [140]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #assigning an image to the variable 
card_url_tail = ".png" 

In [126]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [127]:
i = np.random.randint(4) #4 for the amount of suits
j = np.random.randint(13) #13 for the amount of number cards

In [143]:
i,j 

(51, 9)

In [129]:
suit[i]

'p'

In [130]:
card[j]

'10'

In [131]:
from IPython.core.display import display, HTML

In [132]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [133]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [146]:
show_img(img) #testing the code above

In [135]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [142]:
card_image(3) #the suit and number of the 3rd card in the deck

'k4'

In [138]:
img = card_url_head + card_image(3) + card_url_tail

In [137]:
show_img(img)

In [139]:
for i in range(52): 
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)